void generatedart() {printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
printf("\n");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
printf("\n");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(DARK_GREY,0);printf("b");
printf(" ");
setclr(DARK_GREY,0);printf("b");
printf(" ");
setclr(DARK_GREY,0);printf("b");
printf(" ");
setclr(DARK_GREY,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
printf("\n");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(DARK_GREY,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(LIGHT_GREY,0);printf("b");
printf(" ");
setclr(LIGHT_GREY,0);printf("b");
printf(" ");
setclr(LIGHT_GREY,0);printf("b");
printf(" ");
setclr(LIGHT_GREY,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_GREY,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
printf("\n");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(DARK_GREY,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(LIGHT_GREY,0);printf("b");
printf(" ");
setclr(LIGHT_GREY,0);printf("b");
printf(" ");
setclr(CYAN,0);printf("b");
printf(" ");
setclr(LIGHT_GREY,0);printf("b");
printf(" ");
setclr(LIGHT_GREY,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(LIGHT_GREY,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
printf("\n");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(DARK_GREY,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(LIGHT_GREY,0);printf("b");
printf(" ");
setclr(CYAN,0);printf("b");
printf(" ");
setclr(LIGHT_GREY,0);printf("b");
printf(" ");
setclr(CYAN,0);printf("b");
printf(" ");
setclr(LIGHT_GREY,0);printf("b");
printf(" ");
setclr(CYAN,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
printf("\n");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(DARK_GREY,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(CYAN,0);printf("b");
printf(" ");
setclr(CYAN,0);printf("b");
printf(" ");
setclr(CYAN,0);printf("b");
printf(" ");
setclr(LIGHT_GREY,0);printf("b");
printf(" ");
setclr(LIGHT_GREY,0);printf("b");
printf(" ");
setclr(LIGHT_GREY,0);printf("b");
printf(" ");
setclr(CYAN,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_GREY,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
printf("\n");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(CYAN,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_GREY,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
printf("\n");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(LIGHT_GREY,0);printf("b");
printf(" ");
setclr(LIGHT_GREY,0);printf("b");
printf(" ");
setclr(LIGHT_GREY,0);printf("b");
printf(" ");
setclr(LIGHT_GREY,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_GREY,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
printf("\n");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_GREY,0);printf("b");
printf(" ");
setclr(DARK_GREY,0);printf("b");
printf(" ");
setclr(DARK_GREY,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(CYAN,0);printf("b");
printf(" ");
setclr(CYAN,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_GREY,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
printf("\n");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(DARK_GREY,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_GREY,0);printf("b");
printf(" ");
setclr(DARK_GREY,0);printf("b");
printf(" ");
setclr(DARK_GREY,0);printf("b");
printf(" ");
setclr(DARK_GREY,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(LIGHT_GREY,0);printf("b");
printf(" ");
setclr(CYAN,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(CYAN,0);printf("b");
printf(" ");
setclr(CYAN,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
printf("\n");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_GREY,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_GREY,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
printf("\n");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(DARK_GREY,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_CYAN,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
printf("\n");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(DARK_GREY,0);printf("b");
printf(" ");
setclr(DARK_GREY,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_BLUE,0);printf("b");
printf(" ");
setclr(DARK_CYAN,0);printf("b");
printf(" ");
setclr(DARK_GREY,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
printf("\n");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
printf("\n");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
setclr(BLACK,0);printf("b");
printf(" ");
printf("\n");
}
